cp OUTPUT_FILE/MD/GAS_FILE/config.out OUTPUT_FILE/MD/GAS_FILE/EQUILIBRAZIONE/config.out
cp OUTPUT_FILE/MD/GAS_FILE/velocity.out OUTPUT_FILE/MD/GAS_FILE/EQUILIBRAZIONE/velocity.out
mv OUTPUT_FILE/MD/GAS_FILE/output_temp.dat OUTPUT_FILE/MD/GAS_FILE/EQUILIBRAZIONE/output_temp.dat
mv OUTPUT_FILE/MD/GAS_FILE/output_etot.dat OUTPUT_FILE/MD/GAS_FILE/EQUILIBRAZIONE/output_etot.dat  
mv OUTPUT_FILE/MD/GAS_FILE/output_ekin.dat OUTPUT_FILE/MD/GAS_FILE/EQUILIBRAZIONE/output_ekin.dat 
mv OUTPUT_FILE/MD/GAS_FILE/output_epot.dat OUTPUT_FILE/MD/GAS_FILE/EQUILIBRAZIONE/output_epot.dat
mv OUTPUT_FILE/MD/GAS_FILE/output_pres.dat OUTPUT_FILE/MD/GAS_FILE/EQUILIBRAZIONE/output_pres.dat
mv OUTPUT_FILE/MD/GAS_FILE/output_gdr.dat OUTPUT_FILE/MD/GAS_FILE/EQUILIBRAZIONE/output_gdr.dat   

cp OUTPUT_FILE/MD/LIQUID_FILE/config.out OUTPUT_FILE/MD/LIQUID_FILE/EQUILIBRAZIONE/config.out
cp OUTPUT_FILE/MD/LIQUID_FILE/velocity.out OUTPUT_FILE/MD/LIQUID_FILE/EQUILIBRAZIONE/velocity.out
mv OUTPUT_FILE/MD/LIQUID_FILE/output_temp.dat OUTPUT_FILE/MD/LIQUID_FILE/EQUILIBRAZIONE/output_temp.dat 
mv OUTPUT_FILE/MD/LIQUID_FILE/output_etot.dat OUTPUT_FILE/MD/LIQUID_FILE/EQUILIBRAZIONE/output_etot.dat  
mv OUTPUT_FILE/MD/LIQUID_FILE/output_ekin.dat OUTPUT_FILE/MD/LIQUID_FILE/EQUILIBRAZIONE/output_ekin.dat 
mv OUTPUT_FILE/MD/LIQUID_FILE/output_epot.dat OUTPUT_FILE/MD/LIQUID_FILE/EQUILIBRAZIONE/output_epot.dat
mv OUTPUT_FILE/MD/LIQUID_FILE/output_pres.dat OUTPUT_FILE/MD/LIQUID_FILE/EQUILIBRAZIONE/output_pres.dat
mv OUTPUT_FILE/MD/LIQUID_FILE/output_gdr.dat OUTPUT_FILE/MD/LIQUID_FILE/EQUILIBRAZIONE/output_gdr.dat   

cp OUTPUT_FILE/MD/SOLID_FILE/config.out OUTPUT_FILE/MD/SOLID_FILE/EQUILIBRAZIONE/config.out
cp OUTPUT_FILE/MD/SOLID_FILE/velocity.out OUTPUT_FILE/MD/SOLID_FILE/EQUILIBRAZIONE/velocity.out
mv OUTPUT_FILE/MD/SOLID_FILE/output_temp.dat OUTPUT_FILE/MD/SOLID_FILE/EQUILIBRAZIONE/output_temp.dat
mv OUTPUT_FILE/MD/SOLID_FILE/output_etot.dat OUTPUT_FILE/MD/SOLID_FILE/EQUILIBRAZIONE/output_etot.dat  
mv OUTPUT_FILE/MD/SOLID_FILE/output_ekin.dat OUTPUT_FILE/MD/SOLID_FILE/EQUILIBRAZIONE/output_ekin.dat 
mv OUTPUT_FILE/MD/SOLID_FILE/output_epot.dat OUTPUT_FILE/MD/SOLID_FILE/EQUILIBRAZIONE/output_epot.dat
mv OUTPUT_FILE/MD/SOLID_FILE/output_pres.dat OUTPUT_FILE/MD/SOLID_FILE/EQUILIBRAZIONE/output_pres.dat
mv OUTPUT_FILE/MD/SOLID_FILE/output_gdr.dat OUTPUT_FILE/MD/SOLID_FILE/EQUILIBRAZIONE/output_gdr.dat   