cp OUTPUT_FILE/MC/GAS_FILE/config.out OUTPUT_FILE/MC/GAS_FILE/EQUILIBRAZIONE_CORRELAZIONE/config.out
cp OUTPUT_FILE/MC/GAS_FILE/velocity.out OUTPUT_FILE/MC/GAS_FILE/EQUILIBRAZIONE_CORRELAZIONE/velocity.out
mv OUTPUT_FILE/MC/GAS_FILE/output_temp.dat OUTPUT_FILE/MC/GAS_FILE/EQUILIBRAZIONE_CORRELAZIONE/output_temp.dat 
mv OUTPUT_FILE/MC/GAS_FILE/output_etot.dat OUTPUT_FILE/MC/GAS_FILE/EQUILIBRAZIONE_CORRELAZIONE/output_etot.dat 
mv OUTPUT_FILE/MC/GAS_FILE/output_ekin.dat OUTPUT_FILE/MC/GAS_FILE/EQUILIBRAZIONE_CORRELAZIONE/output_ekin.dat 
mv OUTPUT_FILE/MC/GAS_FILE/output_epot.dat OUTPUT_FILE/MC/GAS_FILE/EQUILIBRAZIONE_CORRELAZIONE/output_epot.dat
mv OUTPUT_FILE/MC/GAS_FILE/output_pres.dat OUTPUT_FILE/MC/GAS_FILE/EQUILIBRAZIONE_CORRELAZIONE/output_pres.dat
mv OUTPUT_FILE/MC/GAS_FILE/output_gdr.dat OUTPUT_FILE/MC/GAS_FILE/EQUILIBRAZIONE_CORRELAZIONE/output_gdr.dat   

cp OUTPUT_FILE/MC/LIQUID_FILE/config.out OUTPUT_FILE/MC/LIQUID_FILE/EQUILIBRAZIONE_CORRELAZIONE/config.out
cp OUTPUT_FILE/MC/LIQUID_FILE/velocity.out OUTPUT_FILE/MC/LIQUID_FILE/EQUILIBRAZIONE_CORRELAZIONE/velocity.out
mv OUTPUT_FILE/MC/LIQUID_FILE/output_etot.dat OUTPUT_FILE/MC/LIQUID_FILE/EQUILIBRAZIONE_CORRELAZIONE/output_etot.dat 
mv OUTPUT_FILE/MC/LIQUID_FILE/output_temp.dat OUTPUT_FILE/MC/LIQUID_FILE/EQUILIBRAZIONE_CORRELAZIONE/output_temp.dat 
mv OUTPUT_FILE/MC/LIQUID_FILE/output_ekin.dat OUTPUT_FILE/MC/LIQUID_FILE/EQUILIBRAZIONE_CORRELAZIONE/output_ekin.dat 
mv OUTPUT_FILE/MC/LIQUID_FILE/output_epot.dat OUTPUT_FILE/MC/LIQUID_FILE/EQUILIBRAZIONE_CORRELAZIONE/output_epot.dat
mv OUTPUT_FILE/MC/LIQUID_FILE/output_pres.dat OUTPUT_FILE/MC/LIQUID_FILE/EQUILIBRAZIONE_CORRELAZIONE/output_pres.dat
mv OUTPUT_FILE/MC/LIQUID_FILE/output_gdr.dat OUTPUT_FILE/MC/LIQUID_FILE/EQUILIBRAZIONE_CORRELAZIONE/output_gdr.dat   

cp OUTPUT_FILE/MC/SOLID_FILE/config.out OUTPUT_FILE/MC/SOLID_FILE/EQUILIBRAZIONE_CORRELAZIONE/config.out
cp OUTPUT_FILE/MC/SOLID_FILE/velocity.out OUTPUT_FILE/MC/SOLID_FILE/EQUILIBRAZIONE_CORRELAZIONE/velocity.out
mv OUTPUT_FILE/MC/SOLID_FILE/output_etot.dat OUTPUT_FILE/MC/SOLID_FILE/EQUILIBRAZIONE_CORRELAZIONE/output_etot.dat 
mv OUTPUT_FILE/MC/SOLID_FILE/output_temp.dat OUTPUT_FILE/MC/SOLID_FILE/EQUILIBRAZIONE_CORRELAZIONE/output_temp.dat
mv OUTPUT_FILE/MC/SOLID_FILE/output_ekin.dat OUTPUT_FILE/MC/SOLID_FILE/EQUILIBRAZIONE_CORRELAZIONE/output_ekin.dat 
mv OUTPUT_FILE/MC/SOLID_FILE/output_epot.dat OUTPUT_FILE/MC/SOLID_FILE/EQUILIBRAZIONE_CORRELAZIONE/output_epot.dat
mv OUTPUT_FILE/MC/SOLID_FILE/output_pres.dat OUTPUT_FILE/MC/SOLID_FILE/EQUILIBRAZIONE_CORRELAZIONE/output_pres.dat
mv OUTPUT_FILE/MC/SOLID_FILE/output_gdr.dat OUTPUT_FILE/MC/SOLID_FILE/EQUILIBRAZIONE_CORRELAZIONE/output_gdr.dat   