cp OUTPUT_FILE/GAS_FILE/config.out OUTPUT_FILE/GAS_FILE/EQUILIBRAZIONE/config.out
cp OUTPUT_FILE/GAS_FILE/velocity.out OUTPUT_FILE/GAS_FILE/EQUILIBRAZIONE/velocity.out
cp OUTPUT_FILE/GAS_FILE/output_temp.dat OUTPUT_FILE/GAS_FILE/EQUILIBRAZIONE/output_temp.dat 

cp OUTPUT_FILE/LIQUID_FILE/config.out OUTPUT_FILE/LIQUID_FILE/EQUILIBRAZIONE/config.out
cp OUTPUT_FILE/LIQUID_FILE/velocity.out OUTPUT_FILE/LIQUID_FILE/EQUILIBRAZIONE/velocity.out
cp OUTPUT_FILE/LIQUID_FILE/output_temp.dat OUTPUT_FILE/LIQUID_FILE/EQUILIBRAZIONE/output_temp.dat 

cp OUTPUT_FILE/SOLID_FILE/config.out OUTPUT_FILE/SOLID_FILE/EQUILIBRAZIONE/config.out
cp OUTPUT_FILE/SOLID_FILE/velocity.out OUTPUT_FILE/SOLID_FILE/EQUILIBRAZIONE/velocity.out
cp OUTPUT_FILE/SOLID_FILE/output_temp.dat OUTPUT_FILE/SOLID_FILE/EQUILIBRAZIONE/output_temp.dat